<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SupplySeeder extends Seeder
{
    public function run(): void
    {
        // Récupérer les IDs des catégories
        $papeterieId = DB::table('categories')->where('name', 'Papeterie')->value('id');
        $ecritureId = DB::table('categories')->where('name', 'Écriture')->value('id');
        $rangementId = DB::table('categories')->where('name', 'Rangement')->value('id');
        $autresId = DB::table('categories')->where('name', 'Autres')->value('id');
        $theId = DB::table('categories')->where('name', 'Thé')->value('id');
        // Récupérer les IDs des fournisseurs
        $calipageId = DB::table('suppliers')->where('name', 'Calipage')->value('id');
        $prohdId = DB::table('suppliers')->where('name', 'ProHD')->value('id');
        $madeintheId = DB::table('suppliers')->where('name', 'Made in The')->value('id');

        // Créer les fournitures
        DB::table('supplies')->insert([
            [
                'name' => 'Ramette papier A4',
                'reference' => 'PAP-A4-80',
                'packaging' => 'Carton de 5 ramettes',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stylo BIC bleu',
                'reference' => 'STY-BIC-BL',
                'packaging' => 'Boîte de 50',
                'category_id' => $ecritureId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classeur A4',
                'reference' => 'CLA-A4-80',
                'packaging' => 'Lot de 10',
                'category_id' => $rangementId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thé Noir',
                'reference' => 'THE-001',
                'packaging' => 'Boîte de 100',
                'category_id' => $theId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thé Blanc',
                'reference' => 'THE-002',
                'packaging' => 'Boîte de 100',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Crayon HB',
                'reference' => 'CRA-HB-001',
                'packaging' => 'Boîte de 50',
                'category_id' => $ecritureId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gomme blanche',
                'reference' => 'GOM-WH-001',
                'packaging' => 'Lot de 20',
                'category_id' => $ecritureId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Surligneur jaune',
                'reference' => 'SUR-YE-001',
                'packaging' => 'Boîte de 10',
                'category_id' => $ecritureId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Feuille A3',
                'reference' => 'PAP-A3-80',
                'packaging' => 'Carton de 5 ramettes',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Post-it 76x76mm',
                'reference' => 'POS-76-001',
                'packaging' => 'Lot de 12',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chemise cartonnée',
                'reference' => 'CHE-CAR-001',
                'packaging' => 'Lot de 25',
                'category_id' => $rangementId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Trombones',
                'reference' => 'TRO-MET-001',
                'packaging' => 'Boîte de 100',
                'category_id' => $rangementId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Agenda A4',
                'reference' => 'AGD-A4-001',
                'packaging' => 'Unité',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marqueur tableau blanc',
                'reference' => 'MAR-WH-001',
                'packaging' => 'Boîte de 12',
                'category_id' => $ecritureId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Scotch transparent',
                'reference' => 'SCO-TRA-001',
                'packaging' => 'Lot de 6',
                'category_id' => $rangementId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cahier A4 96p',
                'reference' => 'CAH-A4-96',
                'packaging' => 'Lot de 10',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pince à trombones',
                'reference' => 'PIN-TRO-001',
                'packaging' => 'Boîte de 50',
                'category_id' => $rangementId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Règle 30cm',
                'reference' => 'REG-30-001',
                'packaging' => 'Lot de 20',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Calculatrice',
                'reference' => 'CAL-BAS-001',
                'packaging' => 'Unité',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thé Vert',
                'reference' => 'THE-003',
                'packaging' => 'Boîte de 100',
                'category_id' => $theId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ciseaux',
                'reference' => 'CIS-STA-001',
                'packaging' => 'Unité',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Perforateur 2 trous',
                'reference' => 'PER-2T-001',
                'packaging' => 'Unité',
                'category_id' => $rangementId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bloc-notes A5',
                'reference' => 'BLN-A5-001',
                'packaging' => 'Lot de 10',
                'category_id' => $papeterieId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stabilo vert',
                'reference' => 'STB-GR-001',
                'packaging' => 'Boîte de 10',
                'category_id' => $ecritureId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classeur à levier',
                'reference' => 'CLA-LEV-001',
                'packaging' => 'Unité',
                'category_id' => $rangementId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pile AA',
                'reference' => 'PIL-AA-001',
                'packaging' => 'Boîte de 20',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lampe de bureau',
                'reference' => 'LAM-BUR-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tapis de souris',
                'reference' => 'TAP-SOU-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Clavier USB',
                'reference' => 'CLA-USB-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Souris USB',
                'reference' => 'SOU-USB-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Webcam HD',
                'reference' => 'WEB-HD-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Microphone USB',
                'reference' => 'MIC-USB-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Casque audio',
                'reference' => 'CAS-AUD-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hub USB',
                'reference' => 'HUB-USB-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Câble HDMI',
                'reference' => 'CAB-HDM-001',
                'packaging' => 'Unité',
                'category_id' => $autresId,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Récupérer les IDs des fournitures créées
        $papierA4Id = DB::table('supplies')->where('reference', 'PAP-A4-80')->value('id');
        $styloId = DB::table('supplies')->where('reference', 'STY-BIC-BL')->value('id');
        $classeurId = DB::table('supplies')->where('reference', 'CLA-A4-80')->value('id');

        // Créer les liens avec les fournisseurs
        DB::table('supplier_supply')->insert([
            // Liens Calipage
            [
                'supply_id' => $papierA4Id,
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-PAP-001',
                'unit_price' => 4.50,
                'catalog_url' => 'https://secof.calipage.fr/produit/ramette-papier-a4-80g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => $styloId,
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-STY-001',
                'unit_price' => 0.35,
                'catalog_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => $classeurId,
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CLA-001',
                'unit_price' => 2.75,
                'catalog_url' => 'https://secof.calipage.fr/produit/classeur-a4-80g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Liens ProHD
            [
                'supply_id' => $papierA4Id,
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-PAP-001',
                'unit_price' => 4.25,
                'catalog_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => $styloId,
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-STY-001',
                'unit_price' => 0.32,
                'catalog_url' => 'https://www.prohd.fr/produit/stylo-bic-cristal',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => $classeurId,
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-CLA-001',
                'unit_price' => 2.50,
                'catalog_url' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Nouvelles relations pour les fournitures ajoutées
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CRA-HB-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CRA-001',
                'unit_price' => 0.25,
                'catalog_url' => 'https://secof.calipage.fr/produit/crayon-hb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'GOM-WH-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-GOM-001',
                'unit_price' => 0.15,
                'catalog_url' => 'https://secof.calipage.fr/produit/gomme-blanche',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'SUR-YE-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-SUR-001',
                'unit_price' => 0.45,
                'catalog_url' => 'https://secof.calipage.fr/produit/surligneur-jaune',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'PAP-A3-80')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-PAP-002',
                'unit_price' => 6.50,
                'catalog_url' => 'https://secof.calipage.fr/produit/ramette-papier-a3-80g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'POS-76-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-POS-001',
                'unit_price' => 3.75,
                'catalog_url' => 'https://secof.calipage.fr/produit/post-it-76x76',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CHE-CAR-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CHE-001',
                'unit_price' => 0.85,
                'catalog_url' => 'https://secof.calipage.fr/produit/chemise-cartonnee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'TRO-MET-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-TRO-001',
                'unit_price' => 1.25,
                'catalog_url' => 'https://secof.calipage.fr/produit/trombones',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'AGD-A4-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-AGD-001',
                'unit_price' => 4.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/agenda-a4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'MAR-WH-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-MAR-001',
                'unit_price' => 0.75,
                'catalog_url' => 'https://secof.calipage.fr/produit/marqueur-tableau-blanc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'SCO-TRA-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-SCO-001',
                'unit_price' => 2.25,
                'catalog_url' => 'https://secof.calipage.fr/produit/scotch-transparent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CAH-A4-96')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CAH-001',
                'unit_price' => 1.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/cahier-a4-96p',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'PIN-TRO-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-PIN-001',
                'unit_price' => 1.50,
                'catalog_url' => 'https://secof.calipage.fr/produit/pince-trombones',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'REG-30-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-REG-001',
                'unit_price' => 0.35,
                'catalog_url' => 'https://secof.calipage.fr/produit/regle-30cm',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CAL-BAS-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CAL-001',
                'unit_price' => 3.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/calculatrice-basique',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CIS-STA-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CIS-001',
                'unit_price' => 2.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/ciseaux',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'PER-2T-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-PER-001',
                'unit_price' => 4.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/perforateur-2-trous',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'BLN-A5-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-BLN-001',
                'unit_price' => 1.25,
                'catalog_url' => 'https://secof.calipage.fr/produit/bloc-notes-a5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'STB-GR-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-STB-001',
                'unit_price' => 0.55,
                'catalog_url' => 'https://secof.calipage.fr/produit/stabilo-vert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CLA-LEV-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CLA-002',
                'unit_price' => 3.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/classeur-levier',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'PIL-AA-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-PIL-001',
                'unit_price' => 5.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/piles-aa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'LAM-BUR-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-LAM-001',
                'unit_price' => 15.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/lampe-bureau',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'TAP-SOU-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-TAP-001',
                'unit_price' => 2.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/tapis-souris',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CLA-USB-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CLA-003',
                'unit_price' => 12.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/clavier-usb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'SOU-USB-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-SOU-001',
                'unit_price' => 8.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/souris-usb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'WEB-HD-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-WEB-001',
                'unit_price' => 25.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/webcam-hd',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'MIC-USB-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-MIC-001',
                'unit_price' => 15.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/microphone-usb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CAS-AUD-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CAS-001',
                'unit_price' => 19.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/casque-audio',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'HUB-USB-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-HUB-001',
                'unit_price' => 12.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/hub-usb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CAB-HDM-001')->value('id'),
                'supplier_id' => $calipageId,
                'supplier_reference' => 'CAL-CAB-001',
                'unit_price' => 8.95,
                'catalog_url' => 'https://secof.calipage.fr/produit/cable-hdmi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ajout des relations avec ProHD pour environ 20% des fournitures
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CRA-HB-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-CRA-001',
                'unit_price' => 0.23,
                'catalog_url' => 'https://www.prohd.fr/produit/crayon-hb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'GOM-WH-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-GOM-001',
                'unit_price' => 0.14,
                'catalog_url' => 'https://www.prohd.fr/produit/gomme-blanche',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'SUR-YE-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-SUR-001',
                'unit_price' => 0.42,
                'catalog_url' => 'https://www.prohd.fr/produit/surligneur-jaune',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'PAP-A3-80')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-PAP-002',
                'unit_price' => 6.25,
                'catalog_url' => 'https://www.prohd.fr/produit/ramette-papier-a3-80g',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'POS-76-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-POS-001',
                'unit_price' => 3.60,
                'catalog_url' => 'https://www.prohd.fr/produit/post-it-76x76',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'CHE-CAR-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-CHE-001',
                'unit_price' => 0.82,
                'catalog_url' => 'https://www.prohd.fr/produit/chemise-cartonnee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'TRO-MET-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-TRO-001',
                'unit_price' => 1.20,
                'catalog_url' => 'https://www.prohd.fr/produit/trombones',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'AGD-A4-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-AGD-001',
                'unit_price' => 4.75,
                'catalog_url' => 'https://www.prohd.fr/produit/agenda-a4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'MAR-WH-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-MAR-001',
                'unit_price' => 0.72,
                'catalog_url' => 'https://www.prohd.fr/produit/marqueur-tableau-blanc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'SCO-TRA-001')->value('id'),
                'supplier_id' => $prohdId,
                'supplier_reference' => 'PRO-SCO-001',
                'unit_price' => 2.15,
                'catalog_url' => 'https://www.prohd.fr/produit/scotch-transparent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ajout des relations avec Made in The pour les fournitures de thé
            [
                'supply_id' => DB::table('supplies')->where('reference', 'THE-001')->value('id'),
                'supplier_id' => $madeintheId,
                'supplier_reference' => 'MIT-THE-001',
                'unit_price' => 12.95,
                'catalog_url' => 'https://www.grossiste-de-the.fr/produit/the-vert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'THE-002')->value('id'),
                'supplier_id' => $madeintheId,
                'supplier_reference' => 'MIT-THE-002',
                'unit_price' => 12.95,
                'catalog_url' => 'https://www.grossiste-de-the.fr/produit/the-blanc',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'supply_id' => DB::table('supplies')->where('reference', 'THE-003')->value('id'),
                'supplier_id' => $madeintheId,
                'supplier_reference' => 'MIT-THE-003',
                'unit_price' => 12.95,
                'catalog_url' => 'https://www.grossiste-de-the.fr/produit/the-vert',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
